// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAT1ex30y8tD9a8ztztCa150z35r1m4FQ',
    appId: '1:975678801892:web:0f52318788f640a9e8e9f1',
    messagingSenderId: '975678801892',
    projectId: 'eventpro-484a1',
    authDomain: 'eventpro-484a1.firebaseapp.com',
    storageBucket: 'eventpro-484a1.firebasestorage.app',
    measurementId: 'G-243Z2S5CMG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8JFkspykEQhQG0XB8f3jv5iBzo_SAagg',
    appId: '1:975678801892:ios:94f0c3b43cb8d15be8e9f1',
    messagingSenderId: '975678801892',
    projectId: 'eventpro-484a1',
    storageBucket: 'eventpro-484a1.firebasestorage.app',
    iosBundleId: 'com.example.eventPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAT1ex30y8tD9a8ztztCa150z35r1m4FQ',
    appId: '1:975678801892:web:ea1c797ffe8bdadee8e9f1',
    messagingSenderId: '975678801892',
    projectId: 'eventpro-484a1',
    authDomain: 'eventpro-484a1.firebaseapp.com',
    storageBucket: 'eventpro-484a1.firebasestorage.app',
    measurementId: 'G-EV49N4X3CZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8JFkspykEQhQG0XB8f3jv5iBzo_SAagg',
    appId: '1:975678801892:ios:94f0c3b43cb8d15be8e9f1',
    messagingSenderId: '975678801892',
    projectId: 'eventpro-484a1',
    storageBucket: 'eventpro-484a1.firebasestorage.app',
    iosBundleId: 'com.example.eventPro',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiy5w36pLBZs0QU6GLpXW-YctwCpgkZNI',
    appId: '1:975678801892:android:a079bcc926457fdae8e9f1',
    messagingSenderId: '975678801892',
    projectId: 'eventpro-484a1',
    storageBucket: 'eventpro-484a1.firebasestorage.app',
  );

}